blank_issues_enabled: false
contact_links:
  - name: Bug Reports
    url: https://github.com/alexanderdunlop/mentis/issues/new?template=bug_report.yml
    about: Please post bug reports here.
  - name: Questions
    url: https://github.com/alexanderdunlop/mentis/discussions/new?category=q-a
    about: Please post questions here.
  - name: Ideas
    url: https://github.com/alexanderdunlop/mentis/discussions/new?category=ideas
    about: Please post ideas here.
  - name: Other Discussions
    url: https://github.com/alexanderdunlop/mentis/discussions/new/choose
    about: Please post ideas and general discussions here.
